# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.3.0
    working_directory: ~/repo
    # TODO: (bdietz) - think about adding a caching step to speed up the download speeds for deps

    steps:
      - checkout
      - run: npm install
      - run: npm run build

  lint:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - run: npm run deploy:storybook
      - run: cd build && ../node_modules/.bin/semantic-release

workflows:
  version: 2
  build-and-lint:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /feature.*/

  build-lint-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - lint:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
